# This is a templated file from https://github.com/zxiiro-testorg/.zxdog/blob/main/otterdog/blueprints/require_dependabot.yml for test-repo
name: Dependabot auto-merge
on: pull_request_target

permissions: read-all

jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    uses: zxiiro-testorg/.github/.github/workflows/dependabot-auto-merge.yml@main
